exclude: 'docs'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
      - id: check-ast
        name: Check Python Syntax
        description: Simply check whether files parse as valid python.

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--config=config/pyproject.toml]
        language_version: python3.7

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args: [--settings-path=./config/.isort.cfg]
        description: isort is a Python utility / library to sort imports alphabetically, and automatically separated into sections. It provides a command line utility, Python library, and Kate plugin to quickly sort all your imports.

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        args: [--config=./config/.flake8]
        description: Flake8 is a Python library that wraps PyFlakes, pycodestyle and Ned Batchelder’s McCabe script. It is a great toolkit for checking your code base against coding style (PEP8), programming errors (like “library imported but unused” and “Undefined name”) and to check cyclomatic complexity.

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
      - id: pylint
        exclude: 'tests'
        args: [--rcfile=config/.pylintrc]
        description: Pylint is a Python static code analysis tool which looks for programming errors, helps enforcing a coding standard, sniffs for code smells and offers simple refactoring suggestions.
        stages: [push]

  - repo: local
    hooks:
      - id: prepare-commit-msg
        name: prepare-commit-msg
        entry: scripts/prepare_commit_msg.sh
        language: system
        stages: [prepare-commit-msg]

  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.28.1 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: ^(functions|resources|cloudformation)\.(yaml|yml|json)$
